### PR TITLE
Pull Request: Change default colors to look good in Visual Studio's dark theme, removal of monitoring code

### PR DESCRIPTION
**Pull request by neofuturelabs**
I initially made a pull request in the original K1tty branch (link below), but doing it here too, as suggested.

It would be great if you could incorporate these changes in the VS Marketplace version of RockScroll, if they look good to you. Thanks!

Here are my previous comments about this pull request:
https://github.com/K1tty/RockMargin/pull/1

--
I've been a fan of RockScroll/MetalScroll/RockMargin since one of its early iterations. One of the few issues I've had with the extension is how the default colors clash with the color theme of Visual Studio's Dark Mode. Furthermore, it's annoying to have to manually input the ARGB color settings every time after installing the extension.

So here are the two modifications I've included in this pull request (built on top of ArkEcho's VS2022 pull request "pr/1"):

- Changed the default colors and width to look good in Dark Mode. Adjusted the order of settings in the default settings code to match the actual settings order in the Options menu (to make it easier to adjust).
- Removed the Monitoring / IPLookup related code, as sending my IP address, Machine Name, and City to a random server (in Kyiv?) doesn't match my use-case for this extension. I suppose the crash-reporting code could be useful if the extension is being actively maintained (is it?), but I don't see why MonitoringService.SendPresense needs to be called in CreateMargin.

Feel free to integrate or not integrate these commits into the main branch, or any personal branches as you would like.

If anyone wants to really go above-and-beyond, adding a system to select from several default color themes would probably be ideal. Furthermore, I'm not sure why the RockMargin settings aren't properly exported/imported when backing up your Visual Studio user settings, so that might be worth looking into as well.

### CODE REVIEW

**Comment by ArkEcho** [comment]
Hello @neofuturelabs 

like i said in my comment on Kittys Repo, just changing the default Colors would "break" the Extension for everyone using Light Mode (like me ;-) ). Light Mode is the default Theme when installing VS2022 (as far as i know), therefore the default Colors in Rockmargin should represent those. 
A better way would be an "automatic" Mode, so the Color in Rockmargin would change according to the selected Theme. After all, the Rockmargin Scrollbar is just a minimized Version of your Document.

I will remove the Monitoring Service asap. I didn't know there was such a thing implemented for Crash Results.

**Comment by neofuturelabs** [comment]
Thanks for the feedback! No problem. If I have time, I will consider later if there is an easy way to add a theme selector or "automatic" mode.

**Comment by ArkEcho** [comment]
@neofuturelabs I just published an updated Version without the Monitoring/Crash Report. When i ported the Extension to VS2022, i didn't look through all the Sources. I was kinda surprised, that the Extension called Home to a random Server -.-

When I have the Time, i will implement the Automatic Color Selector. Maybe you are willing to do that? Let me know.

**Comment by neofuturelabs** [comment]
@ArkEcho 
Awesome, thanks for the update!
If you have an idea for implementing the automatic color selector, by all means go for it! :)


BTW if you start working on it, check out my commit above which fixes the order of the default settings in the code to match the order in the VS Options screen (otherwise it's pretty confusing, because the names are all different).

For the Dark theme specifically, I recommend the color selection as defined in my commit (or shown below):
rockmargin_settings
292965713-37f0caf7-7f70-47d2-b136-8608dd6e4d2a

**Pull request closed without merging**
